# Generated by Django 4.1.1 on 2022-09-18 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('account', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='read_blogs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wish_list',
        ),
        migrations.CreateModel(
            name='UserWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wish_lists', to=settings.AUTH_USER_MODEL)),
                ('wish_list', models.ManyToManyField(blank=True, related_name='wish_lists', to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='UserReadBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_blogs', models.ManyToManyField(blank=True, related_name='read_blogs', to='blog.blog')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='read_blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
