version: '3.8'

services:
  db:
    restart: always
    image: postgres
    container_name: django-blog-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54035:5432"
    networks:
      - django-blog-network
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    restart: always
    build: ./src
    container_name: django-blog-web
    networks:
      - django-blog-network
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 8000"
    volumes:
      - ./src:/src
      - ./src/main:/src/main
      - ./src/static:/src/static
      - ./src/media:/src/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  static:
    driver: local
  media:
    driver: local
  web:
    driver: local


networks:
  django-blog-network:
    driver: bridge