version: '3.3'

services:
  db:
    image: library/postgres:13.2-alpine
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 54033:5432
    env_file:
      - ./app/.env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn main.wsgi:application --bind 0.0.0.0:9120 --workers 4"
    networks:
      - app-network
    volumes:
      - ./app/core:/app/core
      - media:/app/media
    ports:
      - 9120:9120
    env_file:
      - ./app/.env
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  media:  
    driver: local

networks:
  app-network:
    driver: bridge