version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./src/db:/var/lib/postgres/data
    env_file:
      - ./src/.env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: ./src
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn main.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - db