# Generated by Django 4.1.1 on 2022-12-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_userreadblogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
