# Generated by Django 4.1.1 on 2022-12-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('subject', models.TextField()),
            ],
        ),
    ]
