# Generated by Django 4.1.1 on 2022-12-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userwishlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReadBlogs',
        ),
    ]
